# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultipleAssetsSelection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultipleAssetsSelection

end

target 'MultipleMediaDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'SnapKit', '~> 4.0.0'
   pod "Device", '~> 3.1.2'

end
